### ISSUE TITLE
oauth2 error in napche/azure-vm-client": "^0.0.3"

### ISSUE THREAD

**Issue by ghainbach** [Napche/azure-vm-client#2]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://login.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/token [status code] 400 [reason phrase] Bad Request' in C:\wamp64\www\test\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:89
Stack trace:
#0 C:\wamp64\www\test\vendor\guzzlehttp\guzzle\src\Subscriber\HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 C:\wamp64\www\test\vendor\guzzlehttp\guzzle\src\Event\Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 C:\wamp64\www\test\vendor\guzzlehttp\guzzle\src\RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 C:\wamp64\www\test\vendor\guzzlehttp\guzzle\src\RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#4 C:\wamp64\www\test\vendor\react\promise in C:\wamp64\www\test\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 89

Is this a dependency error with GuzzleHttp? I do have oauth2 working with napche/azure-vm-client": "^0.0.2"

**Comment by Napche** [comment]
You are probably right. I am looking into another issue with guzzle6 compliancy atm. My first guess is this is caused by the same issue. Hope to have a final solution in a couple of hours.
